# Generated by Django 3.1.5 on 2021-03-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pnr', models.IntegerField()),
                ('source', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('day', models.CharField(max_length=15)),
                ('arrival', models.TimeField(blank=True)),
                ('departure', models.TimeField(blank=True)),
            ],
        ),
    ]
