# Generated by Django 3.1.5 on 2021-04-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
