# Generated by Django 3.1.5 on 2021-04-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_trains_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trains',
            old_name='price',
            new_name='price2s',
        ),
        migrations.AddField(
            model_name='trains',
            name='pricesl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
