# Generated by Django 3.1.5 on 2021-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pnr', models.IntegerField()),
                ('date', models.DateField()),
                ('no', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
