# Generated by Django 3.1.5 on 2021-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='pnr',
        ),
        migrations.AddField(
            model_name='tickets',
            name='ages',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='passangers',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
