# Generated by Django 3.1.5 on 2021-04-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210402_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='total_price',
            new_name='priceof1',
        ),
    ]
