# Generated by Django 3.1.5 on 2021-04-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210402_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='priceof1',
            new_name='total_price',
        ),
    ]
