# Generated by Django 3.1.5 on 2021-04-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_avail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avail',
            old_name='seat',
            new_name='seat2s',
        ),
        migrations.AddField(
            model_name='avail',
            name='seatsl',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
